services:
  mongo:
    image: mongo:4.4
    container_name: fiware-orion-mongo
    command: --nojournal
    ports:
      - "27017:27017"
    networks:
      - fiware

  orion:
    image: fiware/orion
    container_name: fiware-orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo:27017
    networks:
      - fiware

networks:
  fiware:

